# Generated by Django 5.0.3 on 2024-03-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizadorapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tr2',
            old_name='CX',
            new_name='CD',
        ),
        migrations.RemoveField(
            model_name='tr2',
            name='DX',
        ),
    ]
